# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/usr/local/opt/curl/bin:/usr/local/Cellar/libpq/13.1/bin:/Users/abc/go/bin:/Users/abc/.poetry/bin:/usr/local/opt/postgres/bin:/usr/local/go1.16/bin:/Users/abc/.cargo/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/abc/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="spaceship"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git kubectl history emoji encode64 zsh-autosuggestions sudo web-search copydir copyfile copybuffer jsontools)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp


#
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias link-dev-db="ssh -CfNg -L 1433:pgm-uf6bb4803r70379j127810.pg.rds.aliyuncs.com:1921 xxx@aliportal.abcrobot.cloud -p 2018"
alias link-prod-db="ssh -CfNg -L 1433:abc-spf-db.pg.rds.aliyuncs.com:1433 xxx@aliportal.abcrobot.cloud -p 2018"
alias link-aws-db="ssh -CfNg -L 5433:a6e404d6e8d8e4677931969ccfff7d87-8da348f8880cb167.elb.cn-northwest-1.amazonaws.com.cn:5432 xxx@aliportal.abcrobot.cloud -p 2018"
alias link-bi-db='ssh -CfNg -L 1921:pgm-uf6do5r5jm2q7272129250.pg.rds.aliyuncs.com:1921 xxx@aliportal.abcrobot.cloud -p 2018'
alias link-dev-redis='ssh -CfNg -L 6380:dev-redis.abc.cloud:6379 xxx@aliportal.abcrobot.cloud -p 2018'
alias link-prod-redis='ssh -CfNg -L 6379:abccache.redis.rds.aliyuncs.com:6379 xxx@aliportal.abcrobot.cloud -p 2018'
alias link-dev-kafka='kubectl port-forward dev-kafka-0 9092:9092'
alias link-appc-vnc='ssh -CfNg -L 59000:localhost:5901 chyi@172.30.1.14'

# Go
export GO111MODULE=on
export GOPATH=/Users/abc/go
export GOROOT=/usr/local/go1.16

export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0

#
#
# Pyenv
eval "$(pyenv init -)"

# Dapr runtime
export PATH=$PATH:/Users/abc.dapr/bin
